// Generated by @cubs/rqlite-client. Do not edit.
import { defineSchema } from '@cubs/rqlite-client';
import type { TableDescriptor } from '@cubs/rqlite-client/schema';
export const schemaHash = "a3d486f3c0a1c307ee615fa731caca77d5119b596b1546801769b9619bfbdd7a";
export const schemaRegistry = {
  "access_invite_acceptances": {
    "name": "access_invite_acceptances",
    "className": "AccessInviteAcceptanceSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "invite_id",
        "name": "invite_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "user_id",
        "name": "user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "accepted_at",
        "name": "accepted_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      }
    ],
    "indexes": [],
    "foreignKeys": [
      {
        "columns": [
          "user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "invite_id"
        ],
        "table": "access_invites",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [
      [
        "invite_id",
        "user_id"
      ]
    ]
  },
  "access_invites": {
    "name": "access_invites",
    "className": "AccessInviteSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "token_hash",
        "name": "token_hash",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "token_hint",
        "name": "token_hint",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "scope_type",
        "name": "scope_type",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "scope_id",
        "name": "scope_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "role_id",
        "name": "role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "recipient_email",
        "name": "recipient_email",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "author_id",
        "name": "author_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "status",
        "name": "status",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "literal",
          "value": "pending"
        }
      },
      {
        "property": "expires_at",
        "name": "expires_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "acceptance_limit",
        "name": "acceptance_limit",
        "type": "INTEGER",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | number",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "acceptance_count",
        "name": "acceptance_count",
        "type": "INTEGER",
        "nullable": false,
        "primaryKey": false,
        "tsType": "number",
        "default": {
          "kind": "literal",
          "value": 0
        }
      },
      {
        "property": "notified_at",
        "name": "notified_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_access_invites_recipient",
        "columns": [],
        "expressions": [
          "lower(trim(recipient_email))"
        ]
      },
      {
        "name": "idx_access_invites_scope",
        "columns": [
          "scope_type",
          "scope_id",
          "created_at"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "author_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "length(token_hash) = 64",
      "scope_type IN ('organization','workspace','page')",
      "status IN ('pending','accepted','rejected','canceled','expired')",
      "acceptance_limit IS NULL OR acceptance_limit > 0",
      "acceptance_count >= 0"
    ],
    "unique": [
      [
        "token_hash"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "account_verifications": {
    "name": "account_verifications",
    "className": "AccountVerificationSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "user_id",
        "name": "user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "token_hash",
        "name": "token_hash",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "token_hint",
        "name": "token_hint",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "invite_id",
        "name": "invite_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "context",
        "name": "context",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": "{}"
        }
      },
      {
        "property": "expires_at",
        "name": "expires_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "last_sent_at",
        "name": "last_sent_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "consumed_at",
        "name": "consumed_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_account_verifications_active",
        "columns": [
          "user_id"
        ],
        "unique": true,
        "where": "consumed_at IS NULL AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "invite_id"
        ],
        "table": "access_invites",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "length(token_hash) = 64",
      "json_valid(context)"
    ],
    "unique": [
      [
        "token_hash"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "organization_members": {
    "name": "organization_members",
    "className": "OrganizationMemberSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "organization_id",
        "name": "organization_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "user_id",
        "name": "user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "organization_member_role_id",
        "name": "organization_member_role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_organization_members_active",
        "columns": [
          "organization_id",
          "user_id"
        ],
        "unique": true,
        "where": "deleted_at IS NULL"
      },
      {
        "name": "idx_organization_members_user",
        "columns": [
          "user_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "organization_member_role_id",
          "organization_id"
        ],
        "table": "organization_roles",
        "references": [
          "id",
          "organization_id"
        ]
      },
      {
        "columns": [
          "user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "organization_id"
        ],
        "table": "organizations",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "organization_pending_requests": {
    "name": "organization_pending_requests",
    "className": "OrganizationPendingRequestSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "organization_id",
        "name": "organization_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "requester_id",
        "name": "requester_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "notified_emails",
        "name": "notified_emails",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": "[]"
        }
      },
      {
        "property": "status",
        "name": "status",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "literal",
          "value": "pending"
        }
      },
      {
        "property": "accepted_by",
        "name": "accepted_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_by",
        "name": "decided_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_at",
        "name": "decided_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "role_id",
        "name": "role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_organization_pending_requests_open",
        "columns": [
          "organization_id",
          "requester_id"
        ],
        "unique": true,
        "where": "status = 'pending' AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "role_id",
          "organization_id"
        ],
        "table": "organization_roles",
        "references": [
          "id",
          "organization_id"
        ]
      },
      {
        "columns": [
          "decided_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "accepted_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "requester_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "organization_id"
        ],
        "table": "organizations",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(notified_emails)",
      "status IN ('pending','accepted','rejected','canceled','expired')"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "organization_roles": {
    "name": "organization_roles",
    "className": "OrganizationRoleSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "organization_id",
        "name": "organization_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "roles",
        "name": "roles",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json"
      },
      {
        "property": "is_default",
        "name": "is_default",
        "type": "INTEGER",
        "nullable": false,
        "primaryKey": false,
        "tsType": "number",
        "default": {
          "kind": "literal",
          "value": 0
        }
      },
      {
        "property": "system_key",
        "name": "system_key",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_organization_roles_default",
        "columns": [
          "organization_id"
        ],
        "unique": true,
        "where": "is_default = 1 AND deleted_at IS NULL"
      },
      {
        "name": "idx_organization_roles_scope",
        "columns": [
          "organization_id"
        ]
      },
      {
        "name": "idx_organization_roles_system",
        "columns": [
          "organization_id",
          "system_key"
        ],
        "unique": true,
        "where": "system_key IS NOT NULL AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "organization_id"
        ],
        "table": "organizations",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(roles)",
      "is_default IN (0,1)"
    ],
    "unique": [
      [
        "id",
        "organization_id"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "organizations": {
    "name": "organizations",
    "className": "OrganizationSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "data",
        "name": "data",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": "{}"
        }
      },
      {
        "property": "owner_id",
        "name": "owner_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [],
    "foreignKeys": [
      {
        "columns": [
          "owner_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": []
  },
  "page_collaborators": {
    "name": "page_collaborators",
    "className": "PageCollaboratorSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "page_id",
        "name": "page_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "user_id",
        "name": "user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "page_member_role_id",
        "name": "page_member_role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_page_collaborators_active",
        "columns": [
          "page_id",
          "user_id"
        ],
        "unique": true,
        "where": "deleted_at IS NULL"
      },
      {
        "name": "idx_page_collaborators_user",
        "columns": [
          "user_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "page_member_role_id",
          "page_id"
        ],
        "table": "page_roles",
        "references": [
          "id",
          "page_id"
        ]
      },
      {
        "columns": [
          "user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "page_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "page_columns": {
    "name": "page_columns",
    "className": "PageColumnSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "type",
        "name": "type",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "data",
        "name": "data",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "parent_id",
        "name": "parent_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_page_columns_parent_deleted_at",
        "columns": [
          "parent_id",
          "deleted_at"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "parent_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "type IN ('text', 'numeric', 'select', 'date', 'checkbox')"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "page_columns_values": {
    "name": "page_columns_values",
    "className": "PageColumnValueSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "data",
        "name": "data",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "page_column_id",
        "name": "page_column_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "page_id",
        "name": "page_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_page_columns_values_cell",
        "columns": [
          "page_id",
          "page_column_id"
        ],
        "unique": true
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "page_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "page_column_id"
        ],
        "table": "page_columns",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": []
  },
  "page_edges": {
    "name": "page_edges",
    "className": "PageEdgeSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "parent_id",
        "name": "parent_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "child_id",
        "name": "child_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      }
    ],
    "indexes": [
      {
        "name": "idx_page_edges_parent_id",
        "columns": [
          "parent_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "child_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "parent_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [
      [
        "parent_id",
        "child_id"
      ]
    ]
  },
  "page_pending_requests": {
    "name": "page_pending_requests",
    "className": "PagePendingRequestSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "page_id",
        "name": "page_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "requester_id",
        "name": "requester_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "notified_emails",
        "name": "notified_emails",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": "[]"
        }
      },
      {
        "property": "status",
        "name": "status",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "literal",
          "value": "pending"
        }
      },
      {
        "property": "accepted_by",
        "name": "accepted_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_by",
        "name": "decided_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_at",
        "name": "decided_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "role_id",
        "name": "role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_page_pending_requests_open",
        "columns": [
          "page_id",
          "requester_id"
        ],
        "unique": true,
        "where": "status = 'pending' AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "role_id",
          "page_id"
        ],
        "table": "page_roles",
        "references": [
          "id",
          "page_id"
        ]
      },
      {
        "columns": [
          "decided_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "accepted_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "requester_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "page_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(notified_emails)",
      "status IN ('pending','accepted','rejected','canceled','expired')"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "page_roles": {
    "name": "page_roles",
    "className": "PageRoleSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "page_id",
        "name": "page_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "roles",
        "name": "roles",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json"
      },
      {
        "property": "is_default",
        "name": "is_default",
        "type": "INTEGER",
        "nullable": false,
        "primaryKey": false,
        "tsType": "number",
        "default": {
          "kind": "literal",
          "value": 0
        }
      },
      {
        "property": "system_key",
        "name": "system_key",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_page_roles_default",
        "columns": [
          "page_id"
        ],
        "unique": true,
        "where": "is_default = 1 AND deleted_at IS NULL"
      },
      {
        "name": "idx_page_roles_scope",
        "columns": [
          "page_id"
        ]
      },
      {
        "name": "idx_page_roles_system",
        "columns": [
          "page_id",
          "system_key"
        ],
        "unique": true,
        "where": "system_key IS NOT NULL AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "page_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(roles)",
      "is_default IN (0,1)"
    ],
    "unique": [
      [
        "id",
        "page_id"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "pages": {
    "name": "pages",
    "className": "PageSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "title",
        "name": "title",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "data",
        "name": "data",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "owner_id",
        "name": "owner_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_pages_deleted_at",
        "columns": [
          "deleted_at"
        ]
      },
      {
        "name": "idx_pages_owner_id",
        "columns": [
          "owner_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "owner_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "pinned_schedule_pages": {
    "name": "pinned_schedule_pages",
    "className": "PinnedSchedulePageSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "workspace_id",
        "name": "workspace_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "page_id",
        "name": "page_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "pinned_by_user_id",
        "name": "pinned_by_user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "date_column_id",
        "name": "date_column_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "color_column_id",
        "name": "color_column_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_pinned_schedule_pages_workspace_user",
        "columns": [
          "workspace_id",
          "pinned_by_user_id"
        ]
      },
      {
        "name": "idx_pinned_schedule_pages_unique",
        "columns": [
          "workspace_id",
          "pinned_by_user_id",
          "page_id"
        ],
        "unique": true
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "workspace_id"
        ],
        "table": "workspaces",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "page_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "pinned_by_user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "date_column_id"
        ],
        "table": "page_columns",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "color_column_id"
        ],
        "table": "page_columns",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": []
  },
  "users": {
    "name": "users",
    "className": "UserSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "email",
        "name": "email",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "password_hash",
        "name": "password_hash",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "token_version",
        "name": "token_version",
        "type": "INTEGER",
        "nullable": false,
        "primaryKey": false,
        "tsType": "number",
        "default": {
          "kind": "literal",
          "value": 0
        }
      },
      {
        "property": "email_verified_at",
        "name": "email_verified_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_users_email",
        "columns": [
          "email"
        ]
      }
    ],
    "foreignKeys": [],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [
      [
        "email"
      ]
    ]
  },
  "workspace_members": {
    "name": "workspace_members",
    "className": "WorkspaceMemberSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "workspace_id",
        "name": "workspace_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "user_id",
        "name": "user_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "workspace_member_role_id",
        "name": "workspace_member_role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "page_root_id",
        "name": "page_root_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_workspace_members_active",
        "columns": [
          "workspace_id",
          "user_id"
        ],
        "unique": true,
        "where": "deleted_at IS NULL"
      },
      {
        "name": "idx_workspace_members_user",
        "columns": [
          "user_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "workspace_member_role_id",
          "workspace_id"
        ],
        "table": "workspace_roles",
        "references": [
          "id",
          "workspace_id"
        ]
      },
      {
        "columns": [
          "page_root_id"
        ],
        "table": "pages",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "workspace_id"
        ],
        "table": "workspaces",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": [
      [
        "page_root_id"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "workspace_pending_requests": {
    "name": "workspace_pending_requests",
    "className": "WorkspacePendingRequestSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "workspace_id",
        "name": "workspace_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "requester_id",
        "name": "requester_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "notified_emails",
        "name": "notified_emails",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": "[]"
        }
      },
      {
        "property": "status",
        "name": "status",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "literal",
          "value": "pending"
        }
      },
      {
        "property": "accepted_by",
        "name": "accepted_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_by",
        "name": "decided_by",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "decided_at",
        "name": "decided_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "role_id",
        "name": "role_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_workspace_pending_requests_open",
        "columns": [
          "workspace_id",
          "requester_id"
        ],
        "unique": true,
        "where": "status = 'pending' AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "role_id",
          "workspace_id"
        ],
        "table": "workspace_roles",
        "references": [
          "id",
          "workspace_id"
        ]
      },
      {
        "columns": [
          "decided_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "accepted_by"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "requester_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "workspace_id"
        ],
        "table": "workspaces",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(notified_emails)",
      "status IN ('pending','accepted','rejected','canceled','expired')"
    ],
    "unique": [],
    "softDelete": "deleted_at"
  },
  "workspace_roles": {
    "name": "workspace_roles",
    "className": "WorkspaceRoleSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "workspace_id",
        "name": "workspace_id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string"
      },
      {
        "property": "roles",
        "name": "roles",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "Array<unknown> | Record<string, unknown>",
        "codec": "json"
      },
      {
        "property": "is_default",
        "name": "is_default",
        "type": "INTEGER",
        "nullable": false,
        "primaryKey": false,
        "tsType": "number",
        "default": {
          "kind": "literal",
          "value": 0
        }
      },
      {
        "property": "system_key",
        "name": "system_key",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "deleted_at",
        "name": "deleted_at",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_workspace_roles_default",
        "columns": [
          "workspace_id"
        ],
        "unique": true,
        "where": "is_default = 1 AND deleted_at IS NULL"
      },
      {
        "name": "idx_workspace_roles_scope",
        "columns": [
          "workspace_id"
        ]
      },
      {
        "name": "idx_workspace_roles_system",
        "columns": [
          "workspace_id",
          "system_key"
        ],
        "unique": true,
        "where": "system_key IS NOT NULL AND deleted_at IS NULL"
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "workspace_id"
        ],
        "table": "workspaces",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26",
      "json_valid(roles)",
      "is_default IN (0,1)"
    ],
    "unique": [
      [
        "id",
        "workspace_id"
      ]
    ],
    "softDelete": "deleted_at"
  },
  "workspaces": {
    "name": "workspaces",
    "className": "WorkspaceSchema",
    "columns": [
      {
        "property": "id",
        "name": "id",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": true,
        "tsType": "string",
        "generated": "ulid"
      },
      {
        "property": "created_at",
        "name": "created_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "created",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "updated_at",
        "name": "updated_at",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "managed": "updated",
        "default": {
          "kind": "expression",
          "value": "CURRENT_TIMESTAMP"
        }
      },
      {
        "property": "name",
        "name": "name",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "data",
        "name": "data",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | Array<unknown> | Record<string, unknown>",
        "codec": "json",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "organization_id",
        "name": "organization_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      },
      {
        "property": "icon",
        "name": "icon",
        "type": "TEXT",
        "nullable": false,
        "primaryKey": false,
        "tsType": "string",
        "default": {
          "kind": "literal",
          "value": "lucide:boxes"
        }
      },
      {
        "property": "created_by_user_id",
        "name": "created_by_user_id",
        "type": "TEXT",
        "nullable": true,
        "primaryKey": false,
        "tsType": "null | string",
        "default": {
          "kind": "literal",
          "value": null
        }
      }
    ],
    "indexes": [
      {
        "name": "idx_workspaces_organization_id",
        "columns": [
          "organization_id"
        ]
      }
    ],
    "foreignKeys": [
      {
        "columns": [
          "created_by_user_id"
        ],
        "table": "users",
        "references": [
          "id"
        ]
      },
      {
        "columns": [
          "organization_id"
        ],
        "table": "organizations",
        "references": [
          "id"
        ]
      }
    ],
    "checks": [
      "length(id) = 26"
    ],
    "unique": []
  }
} satisfies Record<string, TableDescriptor>;
export interface AccessInviteAcceptanceSchemaRow {
  "id": string;
  "invite_id": string;
  "user_id": string;
  "accepted_at": string;
}
export interface AccessInviteAcceptanceSchemaInsert {
  "id"?: string;
  "invite_id": string;
  "user_id": string;
  "accepted_at"?: string;
}
export interface AccessInviteAcceptanceSchemaUpdate {
  "invite_id"?: string;
  "user_id"?: string;
  "accepted_at"?: string;
}
export interface AccessInviteSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "token_hash": string;
  "token_hint": string;
  "scope_type": string;
  "scope_id": string;
  "role_id": null | string;
  "recipient_email": null | string;
  "author_id": string;
  "status": string;
  "expires_at": null | string;
  "acceptance_limit": null | number;
  "acceptance_count": number;
  "notified_at": null | string;
  "deleted_at": null | string;
}
export interface AccessInviteSchemaInsert {
  "id"?: string;
  "token_hash": string;
  "token_hint": string;
  "scope_type": string;
  "scope_id": string;
  "role_id"?: null | string;
  "recipient_email"?: null | string;
  "author_id": string;
  "status"?: string;
  "expires_at"?: null | string;
  "acceptance_limit"?: null | number;
  "acceptance_count"?: number;
  "notified_at"?: null | string;
  "deleted_at"?: null | string;
}
export interface AccessInviteSchemaUpdate {
  "token_hash"?: string;
  "token_hint"?: string;
  "scope_type"?: string;
  "scope_id"?: string;
  "role_id"?: null | string;
  "recipient_email"?: null | string;
  "author_id"?: string;
  "status"?: string;
  "expires_at"?: null | string;
  "acceptance_limit"?: null | number;
  "acceptance_count"?: number;
  "notified_at"?: null | string;
  "deleted_at"?: null | string;
}
export interface AccountVerificationSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "user_id": string;
  "token_hash": string;
  "token_hint": string;
  "invite_id": null | string;
  "context": Array<unknown> | Record<string, unknown>;
  "expires_at": string;
  "last_sent_at": string;
  "consumed_at": null | string;
  "deleted_at": null | string;
}
export interface AccountVerificationSchemaInsert {
  "id"?: string;
  "user_id": string;
  "token_hash": string;
  "token_hint": string;
  "invite_id"?: null | string;
  "context"?: Array<unknown> | Record<string, unknown>;
  "expires_at": string;
  "last_sent_at"?: string;
  "consumed_at"?: null | string;
  "deleted_at"?: null | string;
}
export interface AccountVerificationSchemaUpdate {
  "user_id"?: string;
  "token_hash"?: string;
  "token_hint"?: string;
  "invite_id"?: null | string;
  "context"?: Array<unknown> | Record<string, unknown>;
  "expires_at"?: string;
  "last_sent_at"?: string;
  "consumed_at"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationMemberSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "organization_id": string;
  "user_id": string;
  "organization_member_role_id": null | string;
  "deleted_at": null | string;
}
export interface OrganizationMemberSchemaInsert {
  "id"?: string;
  "organization_id": string;
  "user_id": string;
  "organization_member_role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationMemberSchemaUpdate {
  "organization_id"?: string;
  "user_id"?: string;
  "organization_member_role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationPendingRequestSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "organization_id": string;
  "requester_id": string;
  "notified_emails": Array<unknown> | Record<string, unknown>;
  "status": string;
  "accepted_by": null | string;
  "decided_by": null | string;
  "decided_at": null | string;
  "role_id": null | string;
  "deleted_at": null | string;
}
export interface OrganizationPendingRequestSchemaInsert {
  "id"?: string;
  "organization_id": string;
  "requester_id": string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationPendingRequestSchemaUpdate {
  "organization_id"?: string;
  "requester_id"?: string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationRoleSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "organization_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default": number;
  "system_key": null | string;
  "deleted_at": null | string;
}
export interface OrganizationRoleSchemaInsert {
  "id"?: string;
  "organization_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationRoleSchemaUpdate {
  "organization_id"?: string;
  "name"?: string;
  "roles"?: Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface OrganizationSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "name": string;
  "data": Array<unknown> | Record<string, unknown>;
  "owner_id": null | string;
}
export interface OrganizationSchemaInsert {
  "id"?: string;
  "name": string;
  "data"?: Array<unknown> | Record<string, unknown>;
  "owner_id"?: null | string;
}
export interface OrganizationSchemaUpdate {
  "name"?: string;
  "data"?: Array<unknown> | Record<string, unknown>;
  "owner_id"?: null | string;
}
export interface PageCollaboratorSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "page_id": string;
  "user_id": string;
  "page_member_role_id": null | string;
  "deleted_at": null | string;
}
export interface PageCollaboratorSchemaInsert {
  "id"?: string;
  "page_id": string;
  "user_id": string;
  "page_member_role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageCollaboratorSchemaUpdate {
  "page_id"?: string;
  "user_id"?: string;
  "page_member_role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageColumnSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "name": null | string;
  "type": null | string;
  "data": null | Array<unknown> | Record<string, unknown>;
  "parent_id": null | string;
  "deleted_at": null | string;
}
export interface PageColumnSchemaInsert {
  "id"?: string;
  "name"?: null | string;
  "type"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "parent_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageColumnSchemaUpdate {
  "name"?: null | string;
  "type"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "parent_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageColumnValueSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "data": null | string;
  "page_column_id": null | string;
  "page_id": null | string;
}
export interface PageColumnValueSchemaInsert {
  "id"?: string;
  "data"?: null | string;
  "page_column_id"?: null | string;
  "page_id"?: null | string;
}
export interface PageColumnValueSchemaUpdate {
  "data"?: null | string;
  "page_column_id"?: null | string;
  "page_id"?: null | string;
}
export interface PageEdgeSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "parent_id": string;
  "child_id": string;
}
export interface PageEdgeSchemaInsert {
  "id"?: string;
  "parent_id": string;
  "child_id": string;
}
export interface PageEdgeSchemaUpdate {
  "parent_id"?: string;
  "child_id"?: string;
}
export interface PagePendingRequestSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "page_id": string;
  "requester_id": string;
  "notified_emails": Array<unknown> | Record<string, unknown>;
  "status": string;
  "accepted_by": null | string;
  "decided_by": null | string;
  "decided_at": null | string;
  "role_id": null | string;
  "deleted_at": null | string;
}
export interface PagePendingRequestSchemaInsert {
  "id"?: string;
  "page_id": string;
  "requester_id": string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PagePendingRequestSchemaUpdate {
  "page_id"?: string;
  "requester_id"?: string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageRoleSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "page_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default": number;
  "system_key": null | string;
  "deleted_at": null | string;
}
export interface PageRoleSchemaInsert {
  "id"?: string;
  "page_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageRoleSchemaUpdate {
  "page_id"?: string;
  "name"?: string;
  "roles"?: Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface PageSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "title": null | string;
  "data": null | Array<unknown> | Record<string, unknown>;
  "owner_id": string;
  "deleted_at": null | string;
}
export interface PageSchemaInsert {
  "id"?: string;
  "title"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "owner_id": string;
  "deleted_at"?: null | string;
}
export interface PageSchemaUpdate {
  "title"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "owner_id"?: string;
  "deleted_at"?: null | string;
}
export interface PinnedSchedulePageSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "workspace_id": string;
  "page_id": string;
  "pinned_by_user_id": string;
  "date_column_id": string;
  "color_column_id": null | string;
}
export interface PinnedSchedulePageSchemaInsert {
  "id"?: string;
  "workspace_id": string;
  "page_id": string;
  "pinned_by_user_id": string;
  "date_column_id": string;
  "color_column_id"?: null | string;
}
export interface PinnedSchedulePageSchemaUpdate {
  "workspace_id"?: string;
  "page_id"?: string;
  "pinned_by_user_id"?: string;
  "date_column_id"?: string;
  "color_column_id"?: null | string;
}
export interface UserSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "name": null | string;
  "email": string;
  "password_hash": null | string;
  "token_version": number;
  "email_verified_at": null | string;
}
export interface UserSchemaInsert {
  "id"?: string;
  "name"?: null | string;
  "email": string;
  "password_hash"?: null | string;
  "token_version"?: number;
  "email_verified_at"?: null | string;
}
export interface UserSchemaUpdate {
  "name"?: null | string;
  "email"?: string;
  "password_hash"?: null | string;
  "token_version"?: number;
  "email_verified_at"?: null | string;
}
export interface WorkspaceMemberSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "workspace_id": string;
  "user_id": string;
  "workspace_member_role_id": null | string;
  "page_root_id": string;
  "deleted_at": null | string;
}
export interface WorkspaceMemberSchemaInsert {
  "id"?: string;
  "workspace_id": string;
  "user_id": string;
  "workspace_member_role_id"?: null | string;
  "page_root_id": string;
  "deleted_at"?: null | string;
}
export interface WorkspaceMemberSchemaUpdate {
  "workspace_id"?: string;
  "user_id"?: string;
  "workspace_member_role_id"?: null | string;
  "page_root_id"?: string;
  "deleted_at"?: null | string;
}
export interface WorkspacePendingRequestSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "workspace_id": string;
  "requester_id": string;
  "notified_emails": Array<unknown> | Record<string, unknown>;
  "status": string;
  "accepted_by": null | string;
  "decided_by": null | string;
  "decided_at": null | string;
  "role_id": null | string;
  "deleted_at": null | string;
}
export interface WorkspacePendingRequestSchemaInsert {
  "id"?: string;
  "workspace_id": string;
  "requester_id": string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface WorkspacePendingRequestSchemaUpdate {
  "workspace_id"?: string;
  "requester_id"?: string;
  "notified_emails"?: Array<unknown> | Record<string, unknown>;
  "status"?: string;
  "accepted_by"?: null | string;
  "decided_by"?: null | string;
  "decided_at"?: null | string;
  "role_id"?: null | string;
  "deleted_at"?: null | string;
}
export interface WorkspaceRoleSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "workspace_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default": number;
  "system_key": null | string;
  "deleted_at": null | string;
}
export interface WorkspaceRoleSchemaInsert {
  "id"?: string;
  "workspace_id": string;
  "name": string;
  "roles": Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface WorkspaceRoleSchemaUpdate {
  "workspace_id"?: string;
  "name"?: string;
  "roles"?: Array<unknown> | Record<string, unknown>;
  "is_default"?: number;
  "system_key"?: null | string;
  "deleted_at"?: null | string;
}
export interface WorkspaceSchemaRow {
  "id": string;
  "created_at": string;
  "updated_at": string;
  "name": null | string;
  "data": null | Array<unknown> | Record<string, unknown>;
  "organization_id": null | string;
  "icon": string;
  "created_by_user_id": null | string;
}
export interface WorkspaceSchemaInsert {
  "id"?: string;
  "name"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "organization_id"?: null | string;
  "icon"?: string;
  "created_by_user_id"?: null | string;
}
export interface WorkspaceSchemaUpdate {
  "name"?: null | string;
  "data"?: null | Array<unknown> | Record<string, unknown>;
  "organization_id"?: null | string;
  "icon"?: string;
  "created_by_user_id"?: null | string;
}
export type SchemaModels = {
  "access_invite_acceptances": { row: AccessInviteAcceptanceSchemaRow; insert: AccessInviteAcceptanceSchemaInsert; update: AccessInviteAcceptanceSchemaUpdate };
  "access_invites": { row: AccessInviteSchemaRow; insert: AccessInviteSchemaInsert; update: AccessInviteSchemaUpdate };
  "account_verifications": { row: AccountVerificationSchemaRow; insert: AccountVerificationSchemaInsert; update: AccountVerificationSchemaUpdate };
  "organization_members": { row: OrganizationMemberSchemaRow; insert: OrganizationMemberSchemaInsert; update: OrganizationMemberSchemaUpdate };
  "organization_pending_requests": { row: OrganizationPendingRequestSchemaRow; insert: OrganizationPendingRequestSchemaInsert; update: OrganizationPendingRequestSchemaUpdate };
  "organization_roles": { row: OrganizationRoleSchemaRow; insert: OrganizationRoleSchemaInsert; update: OrganizationRoleSchemaUpdate };
  "organizations": { row: OrganizationSchemaRow; insert: OrganizationSchemaInsert; update: OrganizationSchemaUpdate };
  "page_collaborators": { row: PageCollaboratorSchemaRow; insert: PageCollaboratorSchemaInsert; update: PageCollaboratorSchemaUpdate };
  "page_columns": { row: PageColumnSchemaRow; insert: PageColumnSchemaInsert; update: PageColumnSchemaUpdate };
  "page_columns_values": { row: PageColumnValueSchemaRow; insert: PageColumnValueSchemaInsert; update: PageColumnValueSchemaUpdate };
  "page_edges": { row: PageEdgeSchemaRow; insert: PageEdgeSchemaInsert; update: PageEdgeSchemaUpdate };
  "page_pending_requests": { row: PagePendingRequestSchemaRow; insert: PagePendingRequestSchemaInsert; update: PagePendingRequestSchemaUpdate };
  "page_roles": { row: PageRoleSchemaRow; insert: PageRoleSchemaInsert; update: PageRoleSchemaUpdate };
  "pages": { row: PageSchemaRow; insert: PageSchemaInsert; update: PageSchemaUpdate };
  "pinned_schedule_pages": { row: PinnedSchedulePageSchemaRow; insert: PinnedSchedulePageSchemaInsert; update: PinnedSchedulePageSchemaUpdate };
  "users": { row: UserSchemaRow; insert: UserSchemaInsert; update: UserSchemaUpdate };
  "workspace_members": { row: WorkspaceMemberSchemaRow; insert: WorkspaceMemberSchemaInsert; update: WorkspaceMemberSchemaUpdate };
  "workspace_pending_requests": { row: WorkspacePendingRequestSchemaRow; insert: WorkspacePendingRequestSchemaInsert; update: WorkspacePendingRequestSchemaUpdate };
  "workspace_roles": { row: WorkspaceRoleSchemaRow; insert: WorkspaceRoleSchemaInsert; update: WorkspaceRoleSchemaUpdate };
  "workspaces": { row: WorkspaceSchemaRow; insert: WorkspaceSchemaInsert; update: WorkspaceSchemaUpdate };
};
export const schema = defineSchema<SchemaModels>({hash: schemaHash, tables: schemaRegistry});
